name: CI

on:
  push:
  pull_request_target:
    types: [labeled]

jobs:
  prepare:
    name: "Prepare"
    runs-on: "ubuntu-22.04"

    permissions:
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
